import { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Initialize custom fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans", // CSS variable for Inter font
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono", // CSS variable for JetBrains Mono font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} bg-gray-100 text-gray-900`} // Custom fonts applied
      >
        {children}
      </body>
    </html>
  );
}
